load "#{Crafter::ROOT}/config/default_scripts.rb"

# All your configuration should happen inside configure block
Crafter.configure do

  # This are projects wide instructions
  add_platform({:platform => :ios, :deployment => 8.0})
  #add_git_ignore
  duplicate_configurations({:store => :release, :profiling => :release})

  # set of options, warnings, static analyser and anything else normal xcode treats as build options
  set_options %w(
    GCC_WARN_CHECK_SWITCH_STATEMENTS
    GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS
    CLANG_WARN_DOCUMENTATION_COMMENTS
    CLANG_WARN_EMPTY_BODY
    GCC_WARN_FOUR_CHARACTER_CONSTANTS
    GCC_WARN_SHADOW
    CLANG_WARN_BOOL_CONVERSION
    CLANG_WARN_CONSTANT_CONVERSION
    GCC_WARN_64_TO_32_BIT_CONVERSION
    CLANG_WARN_ENUM_CONVERSION
    CLANG_WARN_INT_CONVERSION
    CLANG_WARN_IMPLICIT_SIGN_CONVERSION
    GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED
    GCC_WARN_ABOUT_RETURN_TYPE  _ERROR
    GCC_WARN_MISSING_PARENTHESES
    GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS
    GCC_WARN_ABOUT_MISSING_PROTOTYPES
    GCC_WARN_ABOUT_MISSING_NEWLINE
    GCC_WARN_ABOUT_POINTER_SIGNEDNESS
    GCC_WARN_SIGN_COMPARE
    CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION
    GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS
    GCC_TREAT_IMPLICIT_FUNCTION_DECLARATIONS_AS_ERRORS
    GCC_WARN_TYPECHECK_CALLS_TO_PRINTF
    GCC_WARN_UNINITIALIZED_AUTOS  _AGGRESSIVE
    GCC_WARN_UNKNOWN_PRAGMAS
    CLANG_WARN_UNREACHABLE_CODE
    GCC_WARN_UNUSED_FUNCTION
    GCC_WARN_UNUSED_LABEL
    GCC_WARN_UNUSED_VALUE
    GCC_WARN_UNUSED_VARIABLE
    GCC_WARN_SHADOW
    GCC_WARN_64_TO_32_BIT_CONVERSION
    GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS
    GCC_WARN_UNDECLARED_SELECTOR
    GCC_WARN_TYPECHECK_CALLS_TO_PRINTF
    GCC_WARN_UNINITIALIZED_AUTOS
    CLANG_WARN_INT_CONVERSION
    CLANG_WARN_ENUM_CONVERSION
    CLANG_WARN_CONSTANT_CONVERSION
    CLANG_WARN_BOOL_CONVERSION
    CLANG_WARN_EMPTY_BODY
    CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION
    GCC_WARN_64_TO_32_BIT_CONVERSION
    GCC_WARN_ABOUT_MISSING_NEWLINE
    GCC_TREAT_INCOMPATIBLE_POINTER_TYPE_WARNINGS_AS_ERRORS
    CLANG_WANR_IMPLICIT_SIGN_CONVERSION
    CLANG_WARN_DOCUMENTATION_DOCUMENTS

    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS
    GCC_WARN_NON_VIRTUAL_DESTRUCTOR
    GCC_WARN_HIDDEN_VIRTUAL_FUNCTIONS
    GCC_WARN_ABOUT_INVALID_OFFSETOF_MACRO
    CLANG_WARN_CXX0X_EXTENSIONS

    CLANG_WARN_DIRECT_OBJC_ISA_USAGE  _ERROR
    CLANG_WARN__DUPLICATE_METHOD_MATCH
    CLANG_WARN_OBJC_IMPLICIT_ATOMIC_PROPERTIES
    GCC_WARN_ALLOW_INCOMPLETE_PROTOCOL
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS
    GCC_WARN_STRICT_SELECTOR_MATCH
    GCC_WARN_UNDECLARED_SELECTOR
    CLANG_WARN_OBJC_ROOT_CLASS  _ERROR

    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF
    CLANG_WARN_OBJC_EXPLICIT_OWNERSHIP_TYPE
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF
    CLANG_WARN__ARC_BRIDGE_CAST_NONARC

    RUN_CLANG_STATIC_ANALYZER
    CLANG_STATIC_ANALYZER_MODE_ON_ANALYZE_ACTION = Deep
    CLANG_STATIC_ANALYZER_MODE = Deep

    CLANG_ANALYZER_DEADCODE_DEADSTORES
    CLANG_ANALYZER_MEMORY_MANAGEMENT
    CLANG_ANALYZER_GCD

    CLANG_ANALYZER_OBJC_ATSYNC
    CLANG_ANALYZER_OBJC_NSCFERROR
    CLANG_ANALYZER_OBJC_INCOMP_METHOD_TYPES
    CLANG_ANALYZER_OBJC_COLLECTIONS
    CLANG_ANALYZER_OBJC_UNUSED_IVARS
    CLANG_ANALYZER_OBJC_SELF_INIT
    CLANG_ANALYZER_OBJC_RETAIN_COUNT

    CLANG_ANALYZER_SECURITY_FLOATLOOPCOUNTER
    CLANG_ANALYZER_SECURITY_KEYCHAIN_API
    CLANG_ANALYZER_SECURITY_INSECUREAPI_UNCHECKEDRETURN
    CLANG_ANALYZER_SECURITY_INSECUREAPI_GETPW_GETS
    CLANG_ANALYZER_SECURITY_INSECUREAPI_MKSTEMP
    CLANG_ANALYZER_SECURITY_INSECUREAPI_RAND
    CLANG_ANALYZER_SECURITY_INSECUREAPI_STRCPY
    CLANG_ANALYZER_SECURITY_INSECUREAPI_VFORK

    RUN_CLANG_STATIC_ANALYZER
    GCC_TREAT_WARNINGS_AS_ERRORS
  )

  # target specific options, :default is just a name for you, feel free to call it whatever you like
  with :default do
    # scripts << {:name => 'icon versioning', :script => Crafter.icon_versioning_script}
  end

  with :swift do
    add_option :swift_networking do
      pods << 'Alamofire'
    end
  end

  # more targets setup
  with :tests do
    add_option :kiwi do
      pods << 'Kiwi'
      scripts << {:name => 'command line unit tests', :script => Crafter.command_line_test_script}
    end

    add_option :quick do
      pods << 'Nimble'
      pods << 'Quick'
    end
  end
end
